version: 2.1

orbs:
  python: circleci/python@0.3.2

jobs:
  build-conda:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: conda
      - run:
         command: |
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            source "$HOME/miniconda/etc/profile.d/conda.sh"
            conda config --set always_yes yes
            conda update conda
            sed -i "s/python>=[0-9]\.[0-9]/python=${TRAVIS_PYTHON_VERSION}/g" requirements/environment.yml
            sed -i '/mpi4py/d' requirements/environment.yml
            conda env create -f requirements/environment.yml
            conda activate elephant
            pip install -r requirements/requirements-tests.txt
            pip install coverage coveralls
         name: conda requirements cached
      - python/save-cache:
          key: conda
      - run:
          command: |
            python setup.py install
            python -c "from elephant.spade import HAVE_FIM; assert HAVE_FIM"
            pip list
            pip -V
            python --version
          name: install elephant package
      - run: pip install coveralls nose
      - run:
          command: |
            nosetests --with-coverage --cover-package=elephant
            coveralls
          name: Test & coverage

  build-pip:
    executor: python/default
    steps:
      - checkout
      - python/load-cache:
          key: pip
      - run:
          command: |
            pip install -r requirements/requirements.txt
            pip install -r requirements/requirements-tests.txt
            pip install coverage coveralls
          name: pip requirements cached
      - python/save-cache:
          key: pip
      - run:
          command: |
            python setup.py install
            python -c "from elephant.spade import HAVE_FIM; assert HAVE_FIM"
            pip list
            pip -V
            python --version
          name: install elephant package
      - run: nosetests --with-coverage --cover-package=elephant

workflows:
  main:
    jobs:
      - build-pip
      - build-conda